// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransitOps.Api.Infrastructure.Persistence;

#nullable disable

namespace TransitOps.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransitOpsDbContext))]
    [Migration("20260329225937_ReplacePostgresEnumsWithSmallint")]
    partial class ReplacePostgresEnumsWithSmallint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("UserRole")
                        .HasColumnType("smallint")
                        .HasColumnName("user_role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_app_user_deleted_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_email_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_username_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_role_valid", "\"user_role\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<DateOnly?>("LicenseExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("license_expiry_date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_driver_deleted_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_email_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_employee_code_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_driver_license_number_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("driver", (string)null);
                });

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.ShipmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("event_date");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("TransportId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_shipment_event_created_by_user_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_shipment_event_deleted_at");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_shipment_event_date");

                    b.HasIndex("TransportId")
                        .HasDatabaseName("ix_shipment_event_transport_id");

                    b.ToTable("shipment_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_shipment_event_type_valid", "\"event_type\" IN (0, 1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.Transport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActualDeliveryAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("actual_delivery_at");

                    b.Property<DateTime?>("ActualPickupAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("actual_pickup_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("destination");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("origin");

                    b.Property<DateTime?>("PlannedDeliveryAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("planned_delivery_at");

                    b.Property<DateTime>("PlannedPickupAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("planned_pickup_at");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_transport_deleted_at");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_transport_driver_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_transport_reference_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_transport_status");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_transport_vehicle_id");

                    b.ToTable("transport", null, t =>
                        {
                            t.HasCheckConstraint("ck_transport_actual_dates", "\"actual_pickup_at\" IS NULL OR \"actual_delivery_at\" IS NULL OR \"actual_delivery_at\" >= \"actual_pickup_at\"");

                            t.HasCheckConstraint("ck_transport_planned_dates", "\"planned_delivery_at\" IS NULL OR \"planned_delivery_at\" >= \"planned_pickup_at\"");

                            t.HasCheckConstraint("ck_transport_status_valid", "\"status\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<decimal?>("CapacityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<decimal?>("CapacityM3")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("capacity_m3");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InternalCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plate_number");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_vehicle_deleted_at");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicle_internal_code_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicle_plate_number_active")
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.ToTable("vehicle", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_capacity_kg_non_negative", "\"capacity_kg\" IS NULL OR \"capacity_kg\" >= 0");

                            t.HasCheckConstraint("ck_vehicle_capacity_m3_non_negative", "\"capacity_m3\" IS NULL OR \"capacity_m3\" >= 0");
                        });
                });

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.ShipmentEvent", b =>
                {
                    b.HasOne("TransitOps.Api.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_event_created_by_user");

                    b.HasOne("TransitOps.Api.Domain.Entities.Transport", null)
                        .WithMany()
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_event_transport");
                });

            modelBuilder.Entity("TransitOps.Api.Domain.Entities.Transport", b =>
                {
                    b.HasOne("TransitOps.Api.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transport_driver");

                    b.HasOne("TransitOps.Api.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transport_vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
