@TransitOps.Api_HostAddress = http://localhost:5098

GET {{TransitOps.Api_HostAddress}}/api/v1/health/live
Accept: application/json

###

GET {{TransitOps.Api_HostAddress}}/api/v1/transports
Accept: application/json

###

GET {{TransitOps.Api_HostAddress}}/api/v1/vehicles
Accept: application/json

###

GET {{TransitOps.Api_HostAddress}}/api/v1/drivers
Accept: application/json

###
